### ISSUE TITLE
Skip SVGs to avoid failure notices

### ISSUE THREAD

**Issue by emaildano** [Automattic/regenerate-thumbnails#10]
This is a feature request. I can try to create a pull request for this as-well. When SVGs are in the media library regen thumbnails counts them as an error. Skipping them or listing X number of SVGs skipped would be a better setup.

**Comment by Viper007Bond** [comment]
SVGs aren't supported by WordPress out of the box, so this is pretty low priority.

**Comment by Viper007Bond** [comment]
Not sure what I was on about in my above comment. Of course they aren't supported, hence your ticket. Anyway, yes, they should be ignored.

**Comment by emaildano** [comment]
@Viper007Bond, it makes sense. To get SVGs in WP it takes a bit of editing anyway so it's not a common thing to do.

I image it's something simple like, check mime type, if X than skip it. I don't know of any other mime types that my fit into this but they could go into that array to be skipped.

**Comment by Viper007Bond** [comment]
Yeah, right now I'm looking for `image/*` but I need to be a bit more selective than that when looking for things to resize. I'm guessing there's a helper function somewhere that I need to use instead.

**Comment by Viper007Bond** [comment]
I'm actually going to `Won't Fix` this since SVGs aren't supported out of the box. I'd rather not manually add exceptions for a bunch of unsupported image types. The plugin that's adding SVG support should probably also be hooking into WordPress core and telling WordPress to ignore them.

**Comment by emaildano** [comment]
@Viper007Bond 

It's not a plugin, it's just a filter `add_filter( 'upload_mimes',  'mime_types' );`

I get what you're saying though. It would be a pain to add what types you should skip/not support.

Instead what if you just added the ones you do? That list is much shorter and likely never to change.

`if { png, jpg, jpeg, etc. }`

**Comment by Viper007Bond** [comment]
A plugin is required though to make use of the filter and change the allowed types though. 😉 

As for a whitelist, that's not future proof as for example WordPress added thumbnail PDF support in version 4.7. I'm using core WordPress functions to do the thumbnail generation which means that the list of supported upload types that can be thumbnailed is subject to change. Infact plugins could even add support for more image editor types that support upload types that WordPress doesn't support out of the box.

**Comment by emaildano** [comment]
WP adding support for PDFs would also break this plugin, right? Since they
cannot be resized or regenerated.

Basic gist of this request is skip things that cannot be regenerated. Not
sure how that is up to other plugins or core to handle.

**Comment by Viper007Bond** [comment]
> WP adding support for PDFs would also break this plugin, right? Since they cannot be resized or regenerated.

No, that's exactly my point -- WordPress _can_ potentially make thumbnails for them depending on your server configuration. Support was added in 4.7.

Anyway, what happens when you initially upload a SVG? Well that's exactly what happens when you run my plugin -- it just calls those same thumbnailing functions again. I don't reinvent the wheel and make thumbnails directly. So if a plugin is adding support for new file types and something is going wrong, it needs to be accounting for that because even without my plugin, things happen during initial upload.

**Comment by grappler** [comment]
I don't fully agree. The plugin currently used `wp_generate_attachment_metadata()` to regenerate the images which is also used when uploading the image but the difference being that WordPress does not give me an error. With this plugin I get `"stylelint" (ID 232) failed to resize. The error message was: Unknown failure reason.`

In `wp_generate_attachment_metadata()` there is an extra check that the image can be displayed `file_is_displayable_image()`. Here WordPress skips any files that are not specific image file types. This helps to skip SVG images. 

Here is a patch to not to show the regenerate button if the image is not part of WordPress's whitelist.
https://github.com/grappler/regenerate-thumbnails/commit/242fa1cec2a9ccc423baf2b84315cbc55801c93b

I am not fully sure how you would adapt the database query but maybe the error message could explain what happened in more detail. For example `"stylelint" (ID 232) was skipped as the file format image/svg can't be regernated.`

**Comment by Viper007Bond** [comment]
I can take a second look. Which plugin are you guys using to add SVG support to WordPress?

**Comment by grappler** [comment]
I used https://wordpress.org/plugins/safe-svg/ to test this.

Originally I had only this line of code to allow admins to upload SVG files.
```php
function prefix_svgs_upload_mimes( $mimes ) {
	if( current_user_can( 'administrator' ) ) {
		$mimes['svg'] = 'image/svg+xml';
	}
	return $mimes;
}
add_filter( 'upload_mimes', 'prefix_svgs_upload_mimes' );
```

Other popular plugins are
https://wordpress.org/plugins/svg-support/
https://wordpress.org/plugins/scalable-vector-graphics-svg/

**Comment by grappler** [comment]
As there is no filter in the plugin to allow skipping the regeneration, I could use `wp_generate_attachment_metadata` instead. With the following code the error would be `"stylelint" (ID 232) failed to resize. The error message was: Skipping SVG files.`

```php
add_filter( 'wp_generate_attachment_metadata', function( $metadata, $attachment_id ) {
	if ( 'image/svg+xml' === get_post_mime_type( $attachment_id ) ) {
		return new WP_Error( 'skip_svg_generate', __( 'Skipping SVG files.', 'textdomain' ) );
	}
	return $metadata;
}, 10, 2 );
```

That may be a better solution as it works better with WPCLI too. 
With the extra code:
```
$ wp media regenerate 232
Found 1 image to regenerate.
Warning: Skipping SVG files.
Error: No images regenerated.
```

Without the extra code:
```
$ wp media regenerate 232
Found 1 image to regenerate.
Warning: 1/1 Couldn't regenerate thumbnails for "stylelint" (ID 232).
Error: No images regenerated.
```

**Comment by Viper007Bond** [comment]
If WP-CLI is throwing errors too, then it sounds like the responsibility falls to the plugin that's adding SVG support to make sure that `wp_generate_attachment_metadata()` skips over SVG files, no?

**Comment by Viper007Bond** [comment]
Also the problem with calling `file_is_displayable_image()` is that it would exclude PDFs, which WordPress supports making thumbnail images for.

**Comment by grappler** [comment]
> Also the problem with calling file_is_displayable_image() is that it would exclude PDFs, which WordPress supports making thumbnail images for.

But the plugin already excludes the PDF's with `'image/' != substr( $post->post_mime_type, 0, 6 )`. There is no regenerate thumbnails button on the edit page for PDF's.

**Comment by Viper007Bond** [comment]
[I'm currently rewriting the plugin from scratch](https://github.com/Viper007Bond/regenerate-thumbnails/tree/dev/v3-rewrite) and I'm likely to reevaluate that and all of the other UI code.

So I guess let's just put this issue on hold until I get there. I'll certainly keep all of this in mind though when I'm writing the code! 👍
