### ISSUE TITLE
Support for .webp images?

### ISSUE THREAD

**Issue by roundhill** [Automattic/regenerate-thumbnails#103]
Does the plugins support images in the newer webp format? A user on the forums is stating that it skips them:

https://wordpress.org/support/topic/translafer-webp-image/

**Comment by alexsanford** [comment]
We support the formats that are supported by WordPress, and it appears that webp is not supported yet.

Here is a forum thread on the topic, with some links to trac issues at the bottom - https://wordpress.org/support/topic/add-support-webp-format-imge/

Closing as this is not something we can currently fix on our end.

**Comment by renatho** [comment]
Support to webp introduced in WP 5.8:
https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/
