### ISSUE TITLE
Support for WordPress 4.0 media grid

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/regenerate-thumbnails#11]
The `media_row_actions` filter is not being used in the 4.0 media grid, nor its pop-up modal windows. 
There's a trac ticket about this already, but it is marked as 'wontfix'  and Helen suggests using the `attachment_fields_to_edit` filter. Based on Swift's reply in the trac ticket, I've come up with the following:

```
add_action( 'attachment_fields_to_edit',                array($this, 'addMediaModalAction'), 10, 2 );
```

and the callback

```
function addMediaModalAction($form_fields, $post) {
        $form_fields["regenerate"] = array(
          'label' => __(""),
          'input' => "html",
          'html' => '<a class="thickbox button" title="Do Something" href="' . admin_url( 'admin-ajax.php' ) . '?action=regeneratethumbnail&id='.$post->ID.'">' . __('Regenerate thumbnails','regenerate-thumbnails') . '</a>',
          'show_in_edit' => false,
        );
        return $form_fields;
    }
```

This results in 

![image](https://cloud.githubusercontent.com/assets/507025/4231927/ac301ada-3996-11e4-995c-9dc3587f2baa.png)

It still definitely needs some scripting to redirecting to the link and to add some error handling/messaging, but it does resize the single image. 

Just throwing this out there for ideas. I'd still love to see the ability to add some actions/filters in the modal area. It seems very hard-coded right now. For example, I think the resize button might make more sense here:

![image](https://cloud.githubusercontent.com/assets/507025/4231925/a2f3fce8-3996-11e4-8137-600f113e8dfe.png)

but there is currently no way to add that.

**Comment by Viper007Bond** [comment]
Thanks for the report. I'll try to take a look soon.

**Comment by helgatheviking** [comment]
That'd be great! I hope the info helps a little.
