### ISSUE TITLE
Incorrect number of attachments on "Regenerate Thumbnails For All X Attachments" button

### ISSUE THREAD

**Issue by alexsanford** [Automattic/regenerate-thumbnails#114]
There seems to be a race condition in the JS code on the Tools > Regenerate Thumbnails page that causes the button to display the incorrect number. When I refresh this page, sometimes the correct number appears, but often it does not.

<img width="397" alt="Screen Shot 2020-10-26 at 14 22 50" src="https://user-images.githubusercontent.com/842193/97206032-20636580-17b0-11eb-8ecf-5cbcc7572397.png">

**Comment by codemonkeynorth** [comment]
~~still happening... the first number should be 12,000+ for my library (it does briefly appear I think but the number on the first button gets overwritten by the number below it on the 2nd button...1116 featured images)~~

fixed in 3.15
