### ISSUE TITLE
Notify if GD & ImageMagick Aren't Available

### ISSUE THREAD

**Issue by devinsays** [Automattic/regenerate-thumbnails#13]
Occasionally servers don't have the required libraries installed for image resizing, which means the script doesn't do anything even though it still runs. I've run into this supporting a couple themes.

I think it would be good for the plugin to throw a notice in these edge cases.

**Comment by Viper007Bond** [comment]
Added in https://github.com/Viper007Bond/regenerate-thumbnails/commit/4f3924e3f1605c659fd53b7d49ab424bb18a591e

**Comment by devinsays** [comment]
Thanks so much! Also, I learned a new function. No idea wp_image_editor_supports existed.

**Comment by Viper007Bond** [comment]
Me either. I stumbled across it while looking at the WP-CLI media regeneration code (I'm in the process of rewriting this plugin).
