### ISSUE TITLE
Add wp-cli command for regenerating thumbnails

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/regenerate-thumbnails#2]
When you're regenerating large numbers of thumbnails, it's better to do it via the CLI than via AJAX requests. I need to add a new [wp-cli](http://wp-cli.org/) command to take care of this.

**Comment by prasadnevase** [comment]
@Viper007Bond could you please tell if this has been implemented? I was searching for solution and landed up here: http://benmay.org/2013/01/27/batch-resizing-45000-images-in-wordpress/ Not sure if this is the solution. Could you please confirm?

**Comment by Viper007Bond** [comment]
No, this functionality has not been added to my plugin yet.

**Comment by prasadnevase** [comment]
If code given in above link is really worth it then can you please add that to your plugin and do a minor release? If yes can you please let me know when will you be releasing it?

**Comment by Viper007Bond** [comment]
The functionality is worth adding but I'm on Windows and I haven't had a chance to get WP-CLI working locally (it requires setting up a virtual machine). That's the main blocker, besides time.

The above link is doesn't need my plugin to run and when I do implement this functionality into my plugin, I'll go about it in a different way that makes use of my existing code.

However if you're capable of setting up and using WP-CLI, then surely you can just use the code at the above link instead of relying on me to add it to my plugin, no?

**Comment by prasadnevase** [comment]
Okay thanks, will take necessary backups and will give it a shot!

**Comment by maor** [comment]
I just love this idea!

**Comment by scribu** [comment]
Note that WP-CLI now has `wp media regenerate` built in.

**Comment by Viper007Bond** [comment]
Cool, then marking this as resolved. :)
