### ISSUE TITLE
Undefined Index Notice

### ISSUE THREAD

**Issue by JD-Robbs** [Automattic/regenerate-thumbnails#20]
Hi there,

Very useful plugin!

When searching for products in my WooCommerce back-end, I get the following notice:

`Notice: Undefined index: action2 in /wp-content/plugins/regenerate-thumbnails/regenerate-thumbnails.php on line 121`

So, I suppose it needs a check for existence before using it.

**Comment by Viper007Bond** [comment]
This will be fixed in v2.3.0. Thanks! :)

**Comment by jabcka** [comment]
Still getting this error after submitting a post:

Notice: Undefined index: action2 in /wp-content/plugins/regenerate-thumbnails/regenerate-thumbnails.php on line 121

**Comment by Viper007Bond** [comment]
As mentioned above, this will be fixed in v2.3.0, which isn't out yet (I'm doing a major overhaul). I don't want to put out a new release just to fix this very minor issue because notices are meant for development environments not production ones so it's not something that you should be seeing. Fix your server's error reporting level. ;)

**Comment by damiankosiorowski** [comment]
**Please verify the problem again and release the patch.**

**Comment by Viper007Bond** [comment]
Crap, I never did release v2.3.0, did I? On my phone right now but I'll try to package it up soon.

**Comment by Viper007Bond** [comment]
It took some work due to mistakes on my part previously but this has _finally_ been released.

**Comment by damiankosiorowski** [comment]
I did not check empirically, but it seems that [the problem](https://github.com/Viper007Bond/regenerate-thumbnails/issues/20#issue-94548968) has not been solved.
https://github.com/Viper007Bond/regenerate-thumbnails/commit/3f8c03b650a88fff989f646ddad828d5574d7fc1#diff-12beb360dbcc6a1a3285b3223bf695bbR170

**Comment by Viper007Bond** [comment]
Ugh, I think you're right. I thought I properly tested this but apparently not. 🤦‍♂️

**Comment by Viper007Bond** [comment]
Fixed (again) and released via v2.3.1.
