### ISSUE TITLE
Add pause button

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/regenerate-thumbnails#21]
I'm already working on overhauling the whole process, but it was suggested that I add a pause button. Makes sense.

See https://wordpress.org/support/topic/feature-request-add-a-pause-button

**Comment by MarceloPedra** [comment]
Thank you!. Just bumping here to get alerted when it's marked as solved. :)

**Comment by Viper007Bond** [comment]
For future reference, if you want alerts you can just click on the subscribe button on the right side under "Notifications" rather than having to leave a comment. :)

**Comment by MarceloPedra** [comment]
Thanks :)

**Comment by nonlinearcom** [comment]
+1

**Comment by itsmrwalsh** [comment]
I know this is probably a bit late now, but I work on some huge WooCommerce sites where people have set their thumbnail setting wrong and I have to undo thousands upon thousands of thumbs and I don't always have SSH access. Throwing my hat in the ring for this +1
