### ISSUE TITLE
PHP 7 Class Method

### ISSUE THREAD

**Issue by robertkent** [Automattic/regenerate-thumbnails#24]
For PHP7 we need to update the class initialisation to use a construct.

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; RegenerateThumbnails has a deprecated constructor in /httpdocs/wp-content/plugins/regenerate-thumbnails/regenerate-thumbnails.php on line 32

**Comment by Viper007Bond** [comment]
Was fixed in https://github.com/Viper007Bond/regenerate-thumbnails/commit/a2e3fdb8167204d53b28300a18031da85a53fa19 in the development version over 3 years ago  which _still_ hasn't been released. I really need to get off my ass and finish this rewrite. :)

**Comment by Viper007Bond** [comment]
For some reason I was thinking that the changes like that had been released while the more major changes I'm currently working on hadn't. Oops.
