### ISSUE TITLE
Allow regenerating of specific sizes

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/regenerate-thumbnails#25]
If only one size is new or modified, then there's no reason to regenerate all sizes.

Easiest way to do this off the top of my head is probably to modify the global thumbnails variable, extract the current meta data from the attachment, regenerate as if only certain sizes existed, and then merge the old meta data with the new.

**Comment by galbaras** [comment]
+1

BTW, this can either mean "let the user choose a size" or "keep the previous sizes, compare and only regenerate what's changed". I'd love to have the second type, because it's less hassle for the user.

**Comment by Viper007Bond** [comment]
https://github.com/Viper007Bond/regenerate-thumbnails/commit/7816522bc9f5eaa185e1bd23de80b11f4a28f6f1 for v3.0.0 partially addresses this by only generating missing thumbnail files by default.

**Comment by Viper007Bond** [comment]
I'm gonna close this in favor of the functionality that only regenerates missing sizes. Easier for the user.

**Comment by galbaras** [comment]
Sorry, just to confirm, there will still be an option to force regeneration of sizes that aren't missing, right?

**Comment by Viper007Bond** [comment]
Yep.

<img width="762" alt="firefox_2017-10-22_09-22-16" src="https://user-images.githubusercontent.com/406254/31863961-883f054c-b70a-11e7-834f-1be58d7011a1.png">

**Comment by galbaras** [comment]
Wow, this is awesome! Showing the media sizes is a very good addition, thank you, and nobody will need "that other regeneration plugin" now to delete old files :)

Given the recommendation for the Delete option, I'd move the Update option down one. This way, checking the boxes when deleting will be done in order.

**Comment by Viper007Bond** [comment]
I made it so that it automatically checks the update posts box if you check the delete box. 😃 

I have it at the bottom as I figured most people won't use it to avoid possible 404s (which I need to update the text to mention).
