### ISSUE TITLE
Update thumbnail URLs in posts

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/regenerate-thumbnails#27]
Posts hard-code the URL to thumbnails meaning that if you change the size of a thumbnail that's used in a post, it's not updated in past posts.

Iterate over posts, regex out the size from the attributes, and then update the `href` tag on the image with the fresh size.

This likely won't make the cut for v3.0.0 but instead a future version.

**Comment by galbaras** [comment]
+1

**Comment by galbaras** [comment]
Actually, if a particular size was selected for a post and it's not removed, why change anything?

On the other hand, if sizes are removed (#28), perhaps embedded images should not be deleted.

**Comment by Viper007Bond** [comment]
Code added to do this in https://github.com/Viper007Bond/regenerate-thumbnails/commit/c7a8c175d1998b89c63495bf1cc32fee7aa6aeb3.

Not closing quite yet as it still needs the UI part.

**Comment by Viper007Bond** [comment]
UI has been handled.
