### ISSUE TITLE
Offer to delete old thumbnails

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/regenerate-thumbnails#28]
Offer to delete old, unused thumbnail sizes. A few things to take into consideration:
- Posts hard-code the URLs to thumbnails so this is going to break posts potentially. Warn users. See also: #27.
- If only resizing certain sizes (see #25), then don't delete other sizes.

Infact, maybe the deletion can be done after by looking at the known thumbnails and then looking for `filename-*x*.ext`, deleting any that aren't in the meta information.

**Comment by Viper007Bond** [comment]
Might make it into v3.0.0 -- we'll see.

**Comment by emdeedee** [comment]
+1 from me!  
I would delete all images, that have -_x_.ext of base images that have had sizes just regenerated.   That would leave images that have been uploaded and forgotten alone, even if they have names such as stock-big-dog-100x200.png
Thanks for the great plugin

**Comment by gretlouise** [comment]
I'd love to see this feature added! It feels ridiculous to leave all the unused images within the site.

**Comment by galbaras** [comment]
Should be good to warn users, but if they choose to delete, just remove anything that doesn't match an existing image size.

+1 from me.

**Comment by galbaras** [comment]
Why not show all the available sizes, label those with inactive sizes as "inactive" and provide checkboxes to direct the regeneration to delete and/or recreate each size?

Making the same interface available for images selected from the media library allows some to be deleted, while others are kept, so uses can do a global job on some sizes and selective jobs on others, if they want to keep some old thumbnails.

This will also be a lot faster than always regenerating all the sizes.

**Comment by Viper007Bond** [comment]
How do you determine if a size is inactive? It could be used within a post. #27 would need to be resolved beforehand.

BTW when you regenerate, only sizes that are currently registered are generated. Old sizes say from old themes aren't regenerated.

**Comment by galbaras** [comment]
[This reply assumes that sizes can be selected]

Alex, as the plugin developer, you don't have to take care of everything for everyone. If you provide options and people use them to mess up their own sites, that's their problem and they should have a backup handy.

It's like a knife manufacturer wanting to ensure nobody would ever use their knife for something bad and not sharpening them. Site owners should be responsible enough to consider the loss of images embedded in posts and make the best choice for their site.

The deletion section should probably display a very prominent warning, which mentions the potential loss of embedded images. Once #27 is resolved, this warning can be removed. Or just changed.

In fact, a good rule may be that embedded images will not deleted. If you can find them, that's a good way to avoid loss of images from content.

Getting really fancy would be an admin page that searches for embedded images of each size to be deleted and lets the user choose what to do.

**Comment by Viper007Bond** [comment]
Also https://github.com/Viper007Bond/regenerate-thumbnails/commit/25a0baef9ea22129dc75065e11ef7a71e4fb5b0e

**Comment by galbaras** [comment]
Hey, Alex, any idea when the thumbnail cleanup functions will be released?

**Comment by Viper007Bond** [comment]
They'll be a part of the v3.0.0 release. I'm not sure when that will be released but I'm hoping this month.
