### ISSUE TITLE
Admin screen heading tags with WordPress 4.4

### ISSUE THREAD

**Issue by lutrov** [Automattic/regenerate-thumbnails#29]
The software uses incorrect headings in admin screens. See https://make.wordpress.org/core/2015/10/28/headings-hierarchy-changes-in-the-admin-screens/ for more.

**Comment by Viper007Bond** [comment]
Thanks!

I've actually already fixed this in the development version I'm working on, but have yet to release:

https://github.com/Viper007Bond/regenerate-thumbnails/blob/0806fdb920fd0b991e94e9870e688b6e67a60a58/regenerate-thumbnails.php#L302

I need to hurry up and finish it so I can release it. I've been working on it way too long...
