### ISSUE TITLE
Keep custom crop

### ISSUE THREAD

**Issue by mawiswiss** [Automattic/regenerate-thumbnails#31]
I'm using the plugin "Manual Image Crop".
Is there a way to keep the custom crop position after thumbnail regeneration?

**Comment by Viper007Bond** [comment]
It'd be on the other plugin to do that.

My plugin calls the WordPress functions that run when you upload an image. Cropping plugins are likely manually overwriting the thumbnail images with their custom crops or whatnot. If they store the crop details in post meta or something, then they can hook into the thumbnail generation code to keep that crop.

Alternatively I want to add the ability to regenerate only certain thumbnail sizes which might result in it not resetting your custom thumbnails if you're only manually editing a certain size.
