### ISSUE TITLE
Site icon sizes lost after thumbnails regenerated

### ISSUE THREAD

**Issue by smerriman** [Automattic/regenerate-thumbnails#34]
WordPress has a special way of creating cropped sizes for site icons (and possibly other images in the customiser?). When thumbnails are regenerated by this plugin, those sizes are overwritten and lost.

This is similar to issue #31, which was closed as it was the responsibility of other plugins to retain their custom sizes. So is it WP core that needs changing, or this plugin?

**Comment by smerriman** [comment]
Also posted here: https://core.trac.wordpress.org/ticket/37311

**Comment by Viper007Bond** [comment]
I can probably add some type of exception to skip over that on my side of things, either determining what's being used as the site icon and ignoring it, or if it's some type of custom size, then ignoring that size.
