### ISSUE TITLE
Link for view / edit thumbnail

### ISSUE THREAD

**Issue by maheshwaghmare** [Automattic/regenerate-thumbnails#38]
Now, It hard to see which thumbnail is regenerated. So, If there is any link added for `view` / `edit` that attachment then we'll be easily navigate to that thumbnail.

**Now It looks like this:**

<img src="http://bsf.io/qf4d9" />

**But, Expected:**
<img src="http://bsf.io/08hu5" />

---

**Comment by Viper007Bond** [comment]
Closing in favor of #39 (no need to open an issue unless you don't plan on submitting a pull request).
