### ISSUE TITLE
Add regenerate link to grid modal and Edit Media page

### ISSUE THREAD

**Issue by Brugman** [Automattic/regenerate-thumbnails#41]
I'd like to have a regenerate link/button on the grid modal and Edit Media pages. Mind if I PR this?

The cursor location in the screenshots below marks the easiest/best positions imo.

![2016-12-29-13-15-07](https://cloud.githubusercontent.com/assets/2203813/21543735/684bbf30-cdc9-11e6-87aa-707482657f7a.png)
![2016-12-29-13-16-03](https://cloud.githubusercontent.com/assets/2203813/21543736/6a7f82dc-cdc9-11e6-8ca6-c38b2ffca01d.png)

**Comment by Viper007Bond** [comment]
Sounds good to me. 👍

**Comment by Viper007Bond** [comment]
This has been added in v2.3.0.

**Comment by Brugman** [comment]
Thanks! I remember getting 1 working quickly and then I forgot about finishing it.
