### ISSUE TITLE
Possibility to regenerate thumbnail images by post type.

### ISSUE THREAD

**Issue by orest22** [Automattic/regenerate-thumbnails#45]
Hey, do you think it's possible to add this feature in nearest future?

**Comment by Viper007Bond** [comment]
They're all of the post type `attachment`. Or are you talking about only regenerating the thumbnails of attachments that are the children of a certain post type?

**Comment by orest22** [comment]
@Viper007Bond Yeah, the second option. Would be nice to have kind of select box with post types. Could be useful for existing websites where user have tons of images, but wants to regenerate only for certain post type.

**Comment by Viper007Bond** [comment]
Did you mean to close this?
