### ISSUE TITLE
Verify useful error messages for invalid images

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/regenerate-thumbnails#46]
https://wordpress.org/support/topic/symbol-in-image-file-name-causes-immediate-unknown-failure/

**Comment by Viper007Bond** [comment]
Yeah, already properly handled. Verified by renaming a PHP file to `.jpg` and then uploading it. Trying to run the plugin on it displays useful error messages.

<img width="224" alt="firefox_2017-11-14_19-34-05" src="https://user-images.githubusercontent.com/406254/32817529-255c9018-c973-11e7-9818-882332671d0b.png">

<img width="353" alt="firefox_2017-11-14_19-35-18" src="https://user-images.githubusercontent.com/406254/32817532-2a09a01a-c973-11e7-8de8-cddc208590a4.png">

**Comment by archon810** [comment]
Sorry, but this wasn't the case for me, as I mentioned. The error message was about an unknown error. The file was not PHP, but a valid image file (webp), which isn't handled by WP. Get a WebP file and rename it as PNG to reproduce.

**Comment by Viper007Bond** [comment]
Right, but you're using the latest stable version (v2.x) and my screenshots are from the upcoming v3.x where a useful error message is displayed. :)

**Comment by archon810** [comment]
Ah, OK, I thought you were saying it was already handled by existing code.
