### ISSUE TITLE
If bulk action redirect URL is too long, possible to redirect using JS and a <form> ?

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/regenerate-thumbnails#47]
https://wordpress.org/support/topic/bug-switch-to-post-requests-for-bulk-regen-because-get-will-reach-url-limit/

Is it possible to ask the server how long of a URL it accepts?

**Comment by archon810** [comment]
Here's a good answer https://stackoverflow.com/a/417184.

**Comment by Viper007Bond** [comment]
I'm pretty sure this isn't fixable by my plugin and is an issue with your server anyway.

As your link says, non-IE browsers should accept stupidly long URLs and servers shouldn't put a limit on the requests.

As for why I can't fix it, the bulk action dropdown that's made by WordPress uses GET, resulting in a URL like this when you use it:

> http://localhost:3000/wp-admin/upload.php?mode=list&attachment-filter=&m=0&s=&_wpnonce=aa8d85c3bc&_wp_http_referer=%2Fwp-admin%2Fupload.php&action=bulk_regenerate_thumbnails&paged=1&media%5B%5D=1793&media%5B%5D=1792&media%5B%5D=1787&media%5B%5D=1785&media%5B%5D=1775&media%5B%5D=1774&media%5B%5D=1768&media%5B%5D=1767&media%5B%5D=1712&media%5B%5D=1709&media%5B%5D=1707&media%5B%5D=1706&media%5B%5D=1699&media%5B%5D=1692&media%5B%5D=1691&media%5B%5D=1690&media%5B%5D=1687&media%5B%5D=1686&media%5B%5D=1628&media%5B%5D=1027&action2=-1&affected=&_ajax_nonce=9516a643de&ps=

I then redirect to my plugin's page with a _shorter_ URL like this:

> http://localhost:3000/wp-admin/tools.php?page=regenerate-thumbnails&ids=1793%2C1792%2C1787%2C1785%2C1775%2C1774%2C1768%2C1767%2C1712%2C1709%2C1707%2C1706%2C1699%2C1692%2C1691%2C1690%2C1687%2C1686%2C1628%2C1027

You should be able to verify that this isn't an issue with my plugin by disabling it, selecting those 600 attachments, and then hitting "Apply" with the default "Bulk Actions" option selected. It won't actually do anything to those attachments but it'll redirect to a very long URL.
