### ISSUE TITLE
Number of total attachments on button changes when leaving/returning to screen

### ISSUE THREAD

**Issue by davewarfel** [Automattic/regenerate-thumbnails#49]
It's a lengthy title, but I couldn't figure out how to be more succinct. Here's a screencast of what is happening:

https://www.dropbox.com/s/klcfp9ns57z8kdx/regen-thumbs-total-attachments-number-changes.mp4?dl=0

The first button that says "Regenerate Thumbnails For All 33 Attachments"... if I click a link (let's say, to jetpack.com or to learn about Photon), and then use my back button to return to the Regenerate Thumbnails screen, the number changes from 33 attachments to 2 attachments. It is worth pointing out that 2 is the number of "featured images only" in my second button.

I wish I knew why this was happening, but unfortunately, I don't. And I realize this is likely a very rare occurrence, but I just thought I'd point it out.

When I clicked the first button to regenerate all attachments, it did process and regenerate all 33. So it worked just fine; it was just that number changed.

**Comment by Viper007Bond** [comment]
Thanks for the bug report! I can reproduce this and I'll try to figure out what's up.

**Comment by davewarfel** [comment]
You're welcome. Let me know if there's anything else I can do to help... or re-test when you've implemented a fix.

P.S. I really like the auto-updating percentage displayed in the `<title>` tag. Nice attention to detail!
