### ISSUE TITLE
Plugin Stalls at Loading Screen

### ISSUE THREAD

**Issue by robertdall** [Automattic/regenerate-thumbnails#50]
In v3.0.0 Beta 20171118 The plugin stalls on the loading screen. 

Steps I took to create the problem: 

1. Downloaded zip of Regenerate thumbnails v3.0.0 Beta 20171118. 
2. Upload via FTP to the staging server.
3. Network Activate
4. Go to main site (site number 1) 
5. Click Regenerate thumbnails under tools
6. All I see is "Regenerate Thumbnails
Loading…"  See attached screenshot: 

<img width="1120" alt="screen shot 2017-12-01 at 12 03 57 pm" src="https://user-images.githubusercontent.com/1909677/33501237-bfbe4f5a-d690-11e7-9b8e-b231125ceae2.png">

System Report from another plugin which might have relevant information about my environment: I have taken out some client identifiable related information.

### Database ###

Database Version: 2.2.5  ✔ Your database is up-to-date.
wp_rg_lead_detail_long:   ✔
wp_rg_lead_notes:   ✔
wp_rg_lead_detail:   ✔
wp_rg_lead:   ✔
wp_rg_form_view:   ✔
wp_rg_form_meta:   ✔
wp_rg_form:   ✔
wp_rg_lead_meta:   ✔
wp_rg_incomplete_submissions:   ✔
wp_gf_addon_feed:   ✔

### WordPress ###

Home URL: http://*****.staging.wpengine.com
Site URL: http://*****.staging.wpengine.com
WordPress Version: 4.8.4 ✔
WordPress Multisite: Yes
WordPress Memory Limit: 512M
WordPress Debug Mode: No
WordPress Debug Log: Yes
WordPress Script Debug Mode: No
WordPress Cron: Yes
WordPress Alternate Cron: No

### Active Plugins ###

Advanced Image Styles: by Gregory Cornelius - 0.4  ✔
Advanced Post Types Order: by Nsp Code - 3.9.6.7  ✔
Akismet Anti-Spam: by Automattic - 3.3.4  ✔
Art Wolfe Image Widget: by 32spokes - 1.0.0  ✔
Black Studio TinyMCE Widget: by Black Studio - 2.4.2  ✔
Categories Images: by Muhammad Said El Zahlan - 2.5.3  ✔
Category Order and Taxonomy Terms Order: by Nsp-Code - 1.4.9  ✔
Comment Moderation E-mail only to Author: by RavanH - 0.5  ✔
IPTC Caption Mapping: by 32spokes - 1.0.0  ✔
Jetpack by WordPress.com: by Automattic - 5.3  ✔
Login Logo: by Mark Jaquith - 0.7  ✔
Manual Control for Jetpack: by Mark Jaquith - 0.2  ✔
Menu Humility: by Mark Jaquith - 0.3  ✔
Menu Social Icons: by Paul Clark - 1.3.10  ✔
Network Nav Menus: by IvyCat Web Services - 1.0.0  ✔
Radio Buttons for Taxonomies: by Kathy Darling - 1.7.7  ✔
Regenerate Thumbnails: by Alex Mills (Viper007Bond) - 3.0.0 Beta  ✔
SendGrid: by SendGrid - 1.9.4  ✔
Simple Local Avatars: by Jake Goldman, 10up - 2.0  ✔
SSL Insecure Content Fixer: by WebAware - 2.4.0  ✔
Stream: by XWP - 3.2.0  ✔
Unattach and Re-attach Media Attachments: by davidn.de - 1.2  ✔
Video Manual for WordPress SEO by Yoast: by Joost de Valk - 1.0.2  ✔
WooCommerce Authorize.Net AIM Gateway: by SkyVerge - 3.11.2  ✔
WooCommerce Smart Coupons: by StoreApps - 3.3.3  ✔
WordPress MU Domain Mapping: by Donncha O Caoimh - 0.5.5.1  ✔
WP Help: by Mark Jaquith - 1.5.3  ✔
WP Hide Post: by scriptburn.com - 2.0.10  ✔
WP Query Multisite: by Eric Lewis, Miguel Peixe, Sergey Biryukov - 1.0  ✔
Yoast SEO: by Team Yoast - 5.4  ✔

### Network Active Plugins ###

Art Wolfe Image Widget: by 32spokes - 1.0.0
Menu Social Icons: by Paul Clark - 1.3.10
Menu Humility: by Mark Jaquith - 0.3
IPTC Caption Mapping: by 32spokes - 1.0.0
WP Help: by Mark Jaquith - 1.5.3
Unattach and Re-attach Media Attachments: by davidn.de - 1.2
Login Logo: by Mark Jaquith - 0.7
Network Nav Menus: by IvyCat Web Services - 1.0.0
WP Query Multisite: by Eric Lewis, Miguel Peixe, Sergey Biryukov - 1.0
Advanced Image Styles: by Gregory Cornelius - 0.4
Simple Local Avatars: by Jake Goldman, 10up - 2.0
Advanced Post Types Order: by Nsp Code - 3.9.6.7
Black Studio TinyMCE Widget: by Black Studio - 2.4.2
Gravity Forms: by rocketgenius - 2.2.5
Yoast SEO: by Team Yoast - 5.4
WooCommerce Authorize.Net AIM Gateway: by SkyVerge - 3.11.2
Jetpack by WordPress.com: by Automattic - 5.3
Manual Control for Jetpack: by Mark Jaquith - 0.2
Stream: by XWP - 3.2.0
WooCommerce Smart Coupons: by StoreApps - 3.3.3
SendGrid: by SendGrid - 1.9.4
SSL Insecure Content Fixer: by WebAware - 2.4.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) - 3.0.0 Beta

### Web Server ###

Software: Apache
Port: 80
Document Root: /nas/wp/www/staging/artwolfe

### PHP ###

Version: 5.6.31-4+wpengine10 ✔
Memory Limit: 512M
Maximum Execution Time: 3600
Maximum File Upload Size: 50M
Maximum File Uploads: 20
Maximum Post Size: 100M
Maximum Input Variables: 1000
cURL Enabled: Yes (version 7.35.0)
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014 (268439663)
Mcrypt Enabled: Yes
Mbstring Enabled: Yes
Loaded Extensions: runkit, Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, mysqlnd, apache2handler, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, msgpack, mysql, mysqli, newrelic, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, mhash, ionCube Loader, Zend OPcache

### MySQL ###

Version: 5.6.37 ✔
Database Character Set: latin1
Database Collation: latin1_swedish_ci

**Comment by Viper007Bond** [comment]
The new version of my plugin is powered by Vue.js, meaning all of the page is rendered using JavaScript. If it's stuck on "Loading...", then the JavaScript isn't working.

You mentioned on Twitter that this was a multisite. Did you install to `plugins` or `mu-plugins`? I'd open the page source and look for `dist/build.js` near the bottom and make sure that the URL is correct and that the file loads.

If it's working, then I'd check your browser's console to see if there's any JavaScript errors.

Or you can just make me an account on the site and DM me the credentials on Twitter and I'll debug it myself if you want. Up to you. :)

**Comment by Viper007Bond** [comment]
Issue was an unbuilt version of the plugin was being used, e.g. no `dist` folder with the compiled JavaScript.
