### ISSUE TITLE
Regeneration Log Style bug

### ISSUE THREAD

**Issue by robertdall** [Automattic/regenerate-thumbnails#51]
Once you get into the triple digits in Regeneration Log the left digit is hidden. 

See Attached Screenshot:  
<img width="603" alt="screen shot 2017-12-01 at 5 18 41 pm" src="https://user-images.githubusercontent.com/1909677/33569733-76875948-d8df-11e7-8d87-06ed5f53a138.png">

**Comment by Viper007Bond** [comment]
Fixed. Thanks!
