### ISSUE TITLE
Move plugin menu link into the Media section

### ISSUE THREAD

**Issue by danieltj27** [Automattic/regenerate-thumbnails#67]
For consistency, I think the plugins link in the dashboard menu should be moved into the Media menu as a submenu item instead for consistency. Whilst it is a useful tool, it's specifically for managing media and seems to fit better into the dashboard flow there.

**Comment by Viper007Bond** [comment]
I get where you're coming from but it's also something that most people rarely use, so it seems to better fit in the Tools menu (it is a tool after all). Plus the tool can be accessed directly from any individual media item or via the bulk actions dropdown menu.

I'm thinking it's better where it is but I'm open to further discussion. :)
