### ISSUE TITLE
Output image sizes during regen process.

### ISSUE THREAD

**Issue by emaildano** [Automattic/regenerate-thumbnails#7]
This isn't an issue but a feature idea. I'd be happy to work on this and create a pull request if you can see it being a possibility.

It would be nice to get a reference of what image sizes are being created. I know most of these dimensions are setup when in my functions file but sometimes I'm not the only one creating these values.

A recap of the dimensions would be great.

Thoughts on this?

**Comment by Viper007Bond** [comment]
Pull request at #8
