### ISSUE TITLE
Feature request: regenerate images by function

### ISSUE THREAD

**Issue by Beee4life** [Automattic/regenerate-thumbnails#70]
If this is an available function already, I apologise, but couldn't find anything.

Can you plz add an option to generate images, based on attachment ID ? 

Something like 

    regenerate_thumbnails( $attachment_id );

**Comment by Viper007Bond** [comment]
```
$regenerator = RegenerateThumbnails_Regenerator::get_instance( $attachment_id );
$regenerator->regenerate();
```

Here's a real world example:

https://github.com/Viper007Bond/regenerate-thumbnails/blob/v3.0.2/includes/class-regeneratethumbnails-rest-controller.php#L166-L207

You can also just hit the REST API: `/wp-json/regenerate-thumbnails/v1/regenerate/12345`

**Comment by Beee4life** [comment]
Respect for the quick reply. I will look at it. Appreciated.
