### ISSUE TITLE
Error regenerating images

### ISSUE THREAD

**Issue by rinseringma** [Automattic/regenerate-thumbnails#76]
When I try to regenerate the thumbnails it throws an error on every image:

`no decode delegate for this image format wp engine`

The site is running on WP Engine, with Offload S3 enabled. It did not occure before and I have contacted WP Engine about it, but they say the command 'wp media regenerate' is running fine in the terminal.

**Comment by Viper007Bond** [comment]
> they say the command 'wp media regenerate' is running fine in the terminal.

How odd. We use almost identical code. Regardless, that error text isn't from my plugin, so I'm really not sure what I can do.
